name: ble_protocol
description: Flutter project to demonstrate the BLE protocol for device

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter_blue_plus: 1.3.1
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.1.2
  permission_handler: ^10.2.0
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
